### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by muhmmadsharjeel** [libindic/indic-trans#20]
I'm trying to install it on my mac but its giving this error

[1/4] Cythonizing indictrans/_decode/beamsearch.pyx
[2/4] Cythonizing indictrans/_decode/viterbi.pyx
[3/4] Cythonizing indictrans/_utils/ctranxn.pyx
[4/4] Cythonizing indictrans/_utils/sparseadd.pyx
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pbr-3.0.0-py2.7.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/Library/Python/2.7/site-packages/pbr-3.0.0-py2.7.egg/pbr/util.py", line 249, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/Library/Python/2.7/site-packages/pbr-3.0.0-py2.7.egg/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/Library/Python/2.7/site-packages/pbr-3.0.0-py2.7.egg/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/Library/Python/2.7/site-packages/pbr-3.0.0-py2.7.egg/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/Library/Python/2.7/site-packages/pbr-3.0.0-py2.7.egg/pbr/packaging.py", line 748, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name indictrans was given, but was not able to be found.
error in setup command: Error parsing /Users/muhammadsharjeel/Desktop/indic-trans-master/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name indictrans was given, but was not able to be found.

**Comment by irshadbhat** [comment]
Looking at the raised Exception, it seems that you tried to setup the package from a zip file.  `indic-trans` uses `pbr` for managing package setup. As described in the raised Exception, versioning for this project requires either an sdist tarball, or access to an upstream git repository. There are two ways to fix this issue:

  You clone the repository, instead of downloading a zip file and run setup.
  Add the following line to `setup.py` file:
    
    import os
    os.environ['PBR_VERSION'] = '1.2.3'

**Comment by muhmmadsharjeel** [comment]
Yap, I cloned the source from the repository and it worked fine.
Thanks.

**Comment by copyninja** [comment]
Since issue is resolved I'm here by closing it.
