### ISSUE TITLE
Transliteration problem

### ISSUE THREAD

**Issue by bharathichezhiyan** [libindic/indic-trans#23]
indictrans  <Ta_June_2017.dev.ta --s tam --t eng --build-lookup >tam_dev_rom.txt
Traceback (most recent call last):
  File "/home/bharaj/anaconda2/bin/indictrans", line 10, in <module>
    sys.exit(main())
  File "/home/bharaj/anaconda2/lib/python2.7/site-packages/indictrans/__init__.py", line 124, in main
    process_args(args)
  File "/home/bharaj/anaconda2/lib/python2.7/site-packages/indictrans/__init__.py", line 110, in process_args
    build_lookup=args.build_lookup)
  File "/home/bharaj/anaconda2/lib/python2.7/site-packages/indictrans/transliterator.py", line 91, in __init__
    i2o = Ind2Target(source, target, decoder, build_lookup)
  File "/home/bharaj/anaconda2/lib/python2.7/site-packages/indictrans/script_transliterate.py", line 22, in __init__
    build_lookup)
  File "/home/bharaj/anaconda2/lib/python2.7/site-packages/indictrans/base.py", line 69, in __init__
    self.base_fit()
  File "/home/bharaj/anaconda2/lib/python2.7/site-packages/indictrans/base.py", line 117, in base_fit
    self.load_models()
  File "/home/bharaj/anaconda2/lib/python2.7/site-packages/indictrans/base.py", line 75, in load_models
    with open('%s/models/%s/sparse.vec' % (self.dist_dir, model)) as jfp:
IOError: [Errno 2] No such file or directory: u'/home/bharaj/anaconda2/lib/python2.7/site-packages/indictrans/models/tam-eng/sparse.vec'

**Comment by irshadbhat** [comment]
I guess the module setup failed to copy the models to the installation directory. Can you share the installation procedure you followed.

**Comment by bharathichezhiyan** [comment]
The problem was I installed in downloaded master directory so It did not update the site-packages dir. I have copied the indictrans dir to the site-packages. it is working now. Thanks.

**Comment by bharathichezhiyan** [comment]
Clone the repository:
    git clone https://github.com/libindic/indictrans.git
Change to the cloned directory:
    cd indic-trans
    pip install -r requirements.txt
    python setup.py install

I followed the same instructions provided by the author.
