### ISSUE TITLE
ValueError: numpy.unfunc size changed

### ISSUE THREAD

**Issue by asifkhan69** [libindic/indic-trans#58]
I have clone repository and successfully build but still receiving this error 
Traceback (most recent call last):
  File "/Users/asifkhan/Development/testenv/bin/indictrans", line 5, in <module>
    from indictrans import main
  File "/Users/asifkhan/Development/testenv/lib/python3.6/site-packages/indictrans/__init__.py", line 9, in <module>
    from ._utils import UrduNormalizer, WX
  File "/Users/asifkhan/Development/testenv/lib/python3.6/site-packages/indictrans/_utils/__init__.py", line 6, in <module>
    from .ctranxn import count_tranxn
  File "indictrans/_utils/ctranxn.pyx", line 1, in init indictrans._utils.ctranxn
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

**Comment by asifkhan69** [comment]
I have upgrade numpy and the above mentioned error resolved. thanks.
